"""
Django settings for project project.

Generated by 'django-admin startproject' using Django 6.0.7.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import os
from pathlib import Path

import dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Load .env file if present (no-op when the file is absent).
dotenv.load_dotenv(BASE_DIR / '.env')


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------

def _int(name: str, default: int) -> int:
    """Return an integer setting from the environment with a fallback default."""
    raw = os.environ.get(name)
    if raw is None:
        return default
    try:
        return int(raw)
    except ValueError:
        return default


def _float(name: str, default: float) -> float:
    """Return a float setting from the environment with a fallback default."""
    raw = os.environ.get(name)
    if raw is None:
        return default
    try:
        return float(raw)
    except ValueError:
        return default


def _str(name: str, default: str) -> str:
    """Return a string setting from the environment with a fallback default."""
    return os.environ.get(name, default)


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = _str('SECRET_KEY', 'django-insecure-51+g$7upr*4u7r31)f%*zf(6xg3un8hos3wlk929^&(5tikq*r')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get('DEBUG', 'true').lower() not in ('false', '0', 'no')

ALLOWED_HOSTS = _str('ALLOWED_HOSTS', '*').split(',')


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'gallery',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'project.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'project.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'
STATICFILES_DIRS = [BASE_DIR / 'static']


# ---------------------------------------------------------------------------
# Cache
# ---------------------------------------------------------------------------

CACHE_TTL = _int('CACHE_TTL', 300)  # seconds

CACHES = {
    'default': {
        'BACKEND': 'django.core.cache.backends.locmem.LocMemCache',
        'TIMEOUT': CACHE_TTL,
    }
}


# ---------------------------------------------------------------------------
# Gallery application settings
# ---------------------------------------------------------------------------

# Base URL for the upstream image provider.
PICSUM_BASE_URL: str = _str('PICSUM_BASE_URL', 'https://picsum.photos')

# Allowed named sizes and their pixel dimensions.
IMAGE_SIZES = {
    'small': 200,
    'medium': 400,
    'large': 800,
}

# Default size name used when none is specified by the user.
IMAGE_DEFAULT_SIZE: str = _str('IMAGE_DEFAULT_SIZE', 'medium')

# Number of images displayed per page (user-configurable via UI, this is the default).
IMAGES_PER_PAGE: int = _int('IMAGES_PER_PAGE', 10)

# Upper bound on image IDs served from the gallery.
# picsum.photos has IDs 0–1084; staying at 1000 keeps all IDs valid.
PICSUM_MAX_IMAGE_ID: int = _int('PICSUM_MAX_IMAGE_ID', 1000)

# ---------------------------------------------------------------------------
# Upstream (picsum.dev) resilience settings
# ---------------------------------------------------------------------------

# Total seconds to wait for a single upstream HTTP response.
UPSTREAM_TIMEOUT_SECONDS: float = _float('UPSTREAM_TIMEOUT_SECONDS', 5.0)

# Maximum number of retry attempts after a transient upstream failure.
UPSTREAM_RETRY_COUNT: int = _int('UPSTREAM_RETRY_COUNT', 3)

# Base backoff in seconds between retries (doubles each attempt).
UPSTREAM_BACKOFF_SECONDS: float = _float('UPSTREAM_BACKOFF_SECONDS', 0.5)


# ---------------------------------------------------------------------------
# Logging — structured JSON to stdout for container visibility
# ---------------------------------------------------------------------------

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'structured': {
            '()': 'gallery.logging.events.StructuredFormatter',
        },
        'simple': {
            'format': '%(asctime)s %(levelname)-8s %(name)s  %(message)s',
        },
    },
    'handlers': {
        'stdout': {
            'class': 'logging.StreamHandler',
            'stream': 'ext://sys.stdout',
            'formatter': 'structured',
        },
    },
    'loggers': {
        # Application loggers — DEBUG and above.
        'gallery': {
            'handlers': ['stdout'],
            'level': 'DEBUG',
            'propagate': False,
        },
    },
    'root': {
        'handlers': ['stdout'],
        'level': 'WARNING',
    },
}

